apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
        - name: hello-web
          # Jenkins will patch this to the exact ECR image:tag
          image: <ECR_URI>:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
